spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate.ddl-auto: update #create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 8080